name: CI 构建
run-name: CI 构建
on:
  workflow_dispatch:
jobs:
  Windows:
    runs-on: windows-latest
    steps:
      - name: 仓库检出
        uses: actions/checkout@v4
      - name: 设置 Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"
      - name: 设置 Miniconda
        uses: conda-incubator/setup-miniconda@v3.1.0
        with:
          activate-environment: Groove
          auto-update-conda: true
          python-version: 3.8
      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -U pyinstaller
          cd app && pyinstaller -w -i resource/images/logo/logo.ico Groove.py
    #  - name: 编译
    #    run:
     #     cd app && pyinstaller -w -i resource/images/logo/logo.ico Groove.py
      - name: 上传
        uses: actions/upload-artifact@v4
        with:
          name: Groove-Windows
          path: app/dist
 # Ubuntu:
